xtensa-esp32-elf-gcc -nostdlib -u call_user_start_cpu0 --entry=app_main \
    -Wl,--gc-sections \
    -Wl,-static \
    -Wl,--start-group \
    -u __cxa_guard_dummy \
    -u __cxx_fatal_exception \
    -L /home/bpugh/esp/esp-idf/components/esp32/ld \
    -T /home/bpugh/esp/win/app/build/esp32/esp32_out.ld \
    -u ld_include_panic_highint_hdl \
    -T esp32.common.ld \
    -T esp32.rom.ld \
    -T esp32.peripherals.ld \
    -T esp32.rom.spiram_incompatible_fns.ld \
    -Wl,--undefined=uxTopUsedPriority \
    -L/home/bpugh/esp/win/app/build/heap -lheap \
    -Wl,--wrap=calloc \
    -Wl,--wrap=malloc \
    -Wl,--wrap=free \
    -Wl,--wrap=realloc \
    -Wl,--wrap=heap_caps_malloc \
    -Wl,--wrap=heap_caps_free \
    -Wl,--wrap=heap_caps_realloc \
    -Wl,--wrap=heap_caps_malloc_default \
    -Wl,--wrap=heap_caps_realloc_default \
    -L/home/bpugh/esp/win/app/build/main -lmain \
    -lgcc -lstdc++ -lgcov \
    -Wl,--end-group \
    -Wl,-EL \
    -o /home/bpugh/esp/win/app/build/ota_app.elf \
    -Wl,-Map=/home/bpugh/esp/win/app/build/ota_app.map
